cli_solver – ForSudoku
cli_solver Subroutine
GPL
18 statements
Source File
public subroutine cli_solver(grid, file)
Provides a solution for a puzzle passed by CLI:
$ ./executable test_in_02.txt
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(9, 9) :: grid
Sudoku Grid
character(len=*), intent(in) :: file
Filepath
Calls
Variables
Type Visibility Attributes Name Initial
logical, public :: presence
Call graph
cli_solver calls display_grid, read_grid, solve_puzzle, valid_grid
solve_puzzle calls list_possible_digits, sort
valid_grid calls valid_colum_or_row, valid_zone