create_puzzle – ForSudoku
create_puzzle Subroutine
GPL
39 statements
Source File
public subroutine create_puzzle(grid, givens)
Creates a puzzle by brute force. But we are not 100% sure that the solution is unique (just a “high” probability).
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(9, 9) :: grid
Sudoku grid.
integer, intent(in) :: givens
Number of given digits in the puzzle.
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: col
integer, public, dimension(9, 9) :: grid0
integer, public :: i
integer, public, parameter :: n = 1000
real, public :: r(2)
integer, public :: row
integer, public, dimension(:, :, :), allocatable :: solutions
logical, public :: unique
Call graph
create_puzzle calls solve_puzzle
solve_puzzle calls list_possible_digits, sort