create_filled_grid – ForSudoku
create_filled_grid Subroutine
GPL
27 statements
Source File
public subroutine create_filled_grid(grid)
Puzzle generators
Grid generation by brute force: in each cycle a digit is added and checked for validity. If the grid becomes invalid, the grid generation is started all over again.
Arguments
Type Intent Optional Attributes Name
integer, intent(out), dimension(9, 9) :: grid
Sudoku grid
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: col
real, public :: r
integer, public :: row
integer, public :: tests
Call graph
create_filled_grid calls valid_digit
valid_digit calls valid_colum_or_row, valid_zone