solve_puzzle – ForSudoku
solve_puzzle Subroutine
GPL
43 statements
Source File
public subroutine solve_puzzle(grid)
Receives a puzzle grid and solves it.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(9, 9) :: grid
Input problem grid and returns solved grid.
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: col
integer, public, dimension(1:81, 1:3) :: empty_cells
integer, public, dimension(9, 9) :: grid0
integer, public :: i
integer, public :: j
integer, public :: nb_empty
integer, public :: nb_possible
integer, public, dimension(1:9) :: possible_digit
real, public :: r
integer, public :: row
Call graph
solve_puzzle calls list_possible_digits, sort
cli_solver calls solve_puzzle
create_puzzle calls solve_puzzle