sort – ForSudoku
sort Subroutine
GPL
20 statements
Source File
public pure subroutine sort(empty_cells, p, n)
Solver routines
Starting from position p, sort the list of empty cells by ascending number of allowed digits. We use a bubble sort algorithm
Arguments
Type Intent Optional Attributes Name
integer, intent(inout), dimension(1:81, 1:3) :: empty_cells
integer, intent(in) :: p
The sort starts at position p (included)
integer, intent(in) :: n
Number of empty cells in the list
Called by
Variables
Type Visibility Attributes Name Initial
integer, public, dimension(1:3) :: col
integer, public :: i
logical, public :: none_swap
Call graph
solve_puzzle calls sort
cli_solver calls solve_puzzle
create_puzzle calls solve_puzzle