valid_zone – ForSudoku
valid_zone Function
GPL
20 statements
Source File
public pure function valid_zone(region)
Validation of a zone/region.
Returns true if each digit in the 3x3 region appears only once.
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(1:3, 1:3) :: region
Sudoku’s subregion
Return Value logical
Called by
Variables
Type Visibility Attributes Name Initial
integer, public :: col
integer, public, dimension(1:9) :: counters
integer, public :: row
Call graph
valid_digit calls valid_zone
valid_grid calls valid_zone
cli_solver calls valid_grid
create_filled_grid calls valid_digit